import chroma from "chroma-js";
//Defining the styles for this component
export default {
  copyText: {
    color: (props) =>
      chroma(props.background).luminance() >= 0.5 ? "black" : "white",
  },
  lightText: {
    color: (props) =>
      chroma(props.background).luminance() >= 0.5 ? "black" : "white",
  },
  seeMore: {
    position: "absolute",
    height: "30px",
    width: "60px",
    bottom: "0",
    fontSize: "0.9rem",
    right: "0%",
    marginLeft: "-50px",
    marginTop: "-15px",
    border: "none",
    background: "rgba(255, 255, 255, 0.3)",
    color: (props) =>
      chroma(props.background).luminance() >= 0.5 ? "black" : "white",
    boxShadow: "none",
    letterSpacing: "1px",
    textTransform: "uppercase",
    outline: "none",
    lineHeight: "30px",
    cursor: "pointer",
    textAlign: "center",
  },
  copyButton: {
    position: "absolute",
    height: "30px",
    width: "100px",
    top: "50%",
    fontSize: "1rem",
    left: "50%",
    marginLeft: "-50px",
    marginTop: "-15px",
    border: "none",
    background: "rgba(255, 255, 255, 0.3)",
    color: (props) =>
      chroma(props.background).luminance() >= 0.5 ? "black" : "white",
    boxShadow: "none",
    opacity: "0",
    textTransform: "uppercase",
    outline: "none",
    lineHeight: "30px",
    cursor: "pointer",
    textDecoration: "none",
  },
  ColorBox: {
    width: "20%",
    height: (props) => (props.more ? "25%" : "50%"),
    display: "inline-block",
    margin: "0 auto",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-5px",
    outline: "none",
    "&:hover": {
      "& $copyButton": {
        opacity: "1",
      },
    },
  },
  boxContent: {
    position: "absolute",
    bottom: "0",
    left: "0",
    fontSize: "12px",
    padding: "10px",
    outline: "none",
    width: "100px",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  colorOverlay: {
    opacity: "0",
    zIndex: "0",
    width: "100%",
    height: "100%",
    transition: "transform 0.6s ease-in-out",
    outline: "none",
    border: "none",
    transform: "scale(0.1)",
  },
  showOverlay: {
    opacity: "1",
    outline: "none",
    border: "none",
    transform: "scale(50)",
    zIndex: "10",
    position: "absolute",
  },
  copyMessage: {
    position: "fixed",
    left: "0",
    top: "0",
    bottom: "0",
    right: "0",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "4rem",
    transform: "scale(0.1)",
    opacity: "0",
    color: "white",
    "& h1": {
      fontWeight: "400",
      textShadow: "1px 2px black",
      background: "rgba(255, 255, 255, 0.2)",
      width: "100%",
      textAlign: "center",
      marginBottom: "0",
      padding: "1rem",
      textTransform: "uppercase",
    },
    "& p": {
      fontSize: "2rem",
      fontWeight: "100",
    },
  },
  copyShow: {
    opacity: "1",
    outline: "none",
    border: "none",
    transform: "scale(1)",
    zIndex: "25",

    transitionDelay: "0.4s",
    transition: "all 0.2s ease-in-out",
  },
};
